version: '3.8'
services:
  nest-api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env.prod
    environment:
      - TZ=Europe/Minsk
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.105.31:12201
    volumes:
      - /home/docnode/files:/var/lib/docker/volumes/app-file-save/_data/files #  первый путь это путь до файлов на СЕРВЕРЕ : второй путь это путь до файлов в контейнере
      - /home/docnode/log:/log #  первый путь это путь до файлов на СЕРВЕРЕ : второй путь это путь до файлов в контейнере
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro

  postgres:
    image: postgres:15
    command: postgres -c 'max_connections=500'
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.prod
    environment:
      - TZ=Europe/Minsk
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      - postgres:/var/lib/postgresql/data
      - ./postgres/pg_hbelt.so:/usr/lib/postgresql/15/lib/pg_hbelt.so:ro
  verapdf:
    image: verapdf/rest
    ports:
      - "4080:8080"
  unoconv:
    image: alphakevin/unoconv-server
    ports:
      - "4000:4000"


volumes:
  postgres:
    name: nest-prisma-docker-db
  nest-api:
    name: app-file-save
